"""empty message

Revision ID: b5ea605cf971
Revises: cca165f1070f
Create Date: 2018-07-29 16:21:11.610723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ea605cf971'
down_revision = 'cca165f1070f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_item_todo_id_fkey', 'todo_item', type_='foreignkey')
    op.create_foreign_key(None, 'todo_item', 'todo', ['todo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_item', type_='foreignkey')
    op.create_foreign_key('todo_item_todo_id_fkey', 'todo_item', 'todo', ['todo_id'], ['id'])
    # ### end Alembic commands ###
